# Generated by Django 5.1.7 on 2025-03-13 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoiceitem_amount_alter_invoiceitem_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
