# Generated by Django 5.1.7 on 2025-03-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_bill_no_alter_invoice_date'),
    ]

    operations = [
    ]
