# Generated by Django 5.1.7 on 2025-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20250313_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_no',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
