# Generated by Django 5.1.7 on 2025-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(max_length=150),
        ),
    ]
