# Generated by Django 5.1.7 on 2025-03-14 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoice_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='BillNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_bill_no', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
