# Generated by Django 5.1.7 on 2025-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_bill_no_billnumbersequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_no',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
