# Generated by Django 5.1.7 on 2025-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_bill_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_bill_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BillNumberSequence',
        ),
    ]
